- hosts: all
  become: yes
  tasks:
    - name: Make the Swap inactive
      command: swapoff -a
    - name: Remove Swap entry from /etc/fstab.
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: Installing Prerequisites for Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: true
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker
        mode: 0600
    - name: Install Docker Engine.
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true
    - name: Enable service docker, and enable persistently
      service:
        name: docker
        enabled: yes

#    - name: install unzip
#      apt:
#        name: unzip
#        state: present
#
#    - name: Download AWS CLI 2
#      unarchive:
#        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
#        dest: ./
#        remote_src: yes
#
#    - name: Install AWS CLI
#      shell: ./aws/install
#
#    - name: Authenticate Docker in AWS ECR
#      shell: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 315727832121.dkr.ecr.us-east-1.amazonaws.com


    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes APT repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: install kubelet
      apt:
        name: kubelet
        state: present
        update_cache: true

    - name: install kubeadm
      apt:
        name: kubeadm
        state: present

- hosts: master
  become: yes
  tasks:
    - name: install kubectl
      apt:
        name: kubectl
        state: present
        force: yes


